### ISSUE TITLE
New PPP Calculator based on latest OCED data

### ISSUE THREAD

**Issue by abishekmuthian** [nigelbabu/pppconverter#11]
Greetings.

I appreciate this converter,  But since this converter is not maintained anymore and that several countries were not included I have built my own [PPP Calculator](https://startuptoolchain.com/calculators/ppp.html) based on latest OCED data.

You're all welcomed to use and contribute towards improving it.

**Comment by malwinder-s** [comment]
You website is not working.. can u pls fix it?

**Comment by abishekmuthian** [comment]
Thanks for informing me, 

Just to clarify, The website was reachable but the calculator is not functioning because the destination county is not working.

I've fixed the error, Please check again - https://startuptoolchain.com/calculators/ppp.html after clearing cache.

**Comment by nigelbabu** [comment]
This is now up to date.
