### ISSUE TITLE
The calculation seems to be wrong

### ISSUE THREAD

**Issue by Rahulaswani** [nigelbabu/pppconverter#4]
Hi @nigelbabu 

I wanted to check what formula are you using to calculate the To_country salary based on the PPP data by world bank and I got this formula from your code

`var equivalent_salary = (Number(salary) / from_country_data.ppp) * to_country_data.ppp; `

[https://github.com/nigelbabu/pppconverter/blob/554f2332c561aab35647a78b7b9cdd67219fe977/static/js/app.js](url)

**Based on which if I do the same calculation in excel as shown below**

![image](https://user-images.githubusercontent.com/6178689/31046652-1840c5d8-a61a-11e7-8502-df24986fe709.png)

![image](https://user-images.githubusercontent.com/6178689/31046625-938c922c-a619-11e7-9c60-7902aed16cf4.png)

**whereas the result by your tool using the same formula show**

![image](https://user-images.githubusercontent.com/6178689/31046630-addd1408-a619-11e7-9fe1-39a20100d834.png)

_Can you please check and tell me if I am doing something wrong ? _

**Comment by nigelbabu** [comment]
A large part of this is because I haven't updated the data recently. I'm working on updating it soon-ish.

**Comment by Rahulaswani** [comment]
thanks, so you are saying since formula is correct hence my excel output is
correct. So I'll use it fir reference at the moment till you get the time
to update this.

Thanks for your help again.

**Comment by nigelbabu** [comment]
The data is now updated.
