### ISSUE TITLE
NaN.N amounts

### ISSUE THREAD

**Issue by ialarmedalien** [nigelbabu/pppconverter#5]
Using your currency converter at http://salaryconverter.nigelb.me, I tried to convert $100,000 into UKP. The result was:

> In United Kingdom, NaN.N GBP will allow you to buy the same things you'd buy with NaN.N USD in United States.

**Comment by VISHAL-RAJ-RAJ** [comment]
@ialarmedalien... Enter the amount without commas

**Comment by nigelbabu** [comment]
Yep, please don't use commas.
